version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build
    overwrite: yes
permissions:
  - object: /home/ubuntu/build
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/before-deploy.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 120
      runas: ubuntu
